### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by harr1193** [harr1193/MI-449-SS17-741-css-intro-iMnt09#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://harr1193.github.io/MI-449-SS17-741-css-intro-iMnt09/) and meets the following criteria:

- [x] Your project is built off [this base HTML and CSS](https://gist.github.com/chrisvfritz/279c36ab6e2301e8a35526be028d8a32) (you may modify both pages however you want, e.g. adding classes or more elements)
- [x] The website looks (nearly) identical to [this mockup](https://i.imgur.com/pGemyxp.png) in the Chrome web browser -- colors must be exact, spacing/sizes should be within about `5px` (use the _Page Ruler_ extension to measure exact sizes/spacing; you might need to open the image in a new tab)
- [x] Any CSS selectors or properties may be used, though the project is possible using only what you saw in the lesson
- [x] No spacing HTML (e.g. `<br>`, `&amp;nbsp;`) is added to `index.html`
- [x] Add at least one link (`a` element) to the page and style them to be `purple` normally, but turn `orange` on hover

**Comment by KatieMFritz** [comment]
Kyle, great job! :boom:

The only thing that doesn't match is the link colors. When we said `purple` and `orange` in the project instructions, we meant the literal [CSS colors](https://css-tricks.com/snippets/css/named-colors-and-hex-equivalents/) named `purple` and `orange`. 😄 

Of course, those colors do have RGB and hex equivalents, and for future projects, RGB, RGBA, and hex are all fine. However, for this project, we want you to use the named colors.

Named colors can be useful for a few reasons:

- typos are more obvious
- it's easier to guess what the color is if you only see the code
- they're great for prototyping or making quick changes - you don't have to memorize codes

Let me know if you have any questions. Otherwise, leave a comment here when you're done! 🎈

**Comment by harr1193** [comment]
Made the changes, that is what I had initially but I thought we needed to use the color picker so I changed it

**Comment by KatieMFritz** [comment]
Ah, got it. :shipit:
